#!/bin/sh
####  PBS preamble

#PBS -N all

#PBS -M kshedden@umich.edu
#PBS -m abe

# Change the number of cores (ppn=1), amount of memory, and walltime:
#PBS -l nodes=1:ppn=16,mem=62gb,walltime=5:00:00
#PBS -j oe
#PBS -V

# Change "example_flux" to the name of your Flux allocation:
#PBS -A stats_flux
#PBS -q flux
#PBS -l qos=flux

####  End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#  Put your job commands here:
export LC_ALL=C
export GOPATH=/home/kshedden/go_projects
export PATH=$PATH:/home/kshedden/go_projects/bin
D="/scratch/andjoh_fluxm/tealfurn/CSCAR/"
H="PRT_NOV_15_02"
F1="30"
F2="60"
NX="10"
CSORT="sort -S 800M --parallel=8"
go run compress_source.go ${H}.fastq
sztool -d ${D}${H}.txt.sz | ${CSORT} | uniq -c | sztool -c - ${D}${H}_sorted.txt.sz
go run window_reads.go ${H}_sorted.txt.sz ${F1} ${F2}
sztool -d ${D}${H}_win_${F1}_${F2}.txt.sz | ${CSORT} -k1 | sztool -c - ${D}${H}_win_${F1}_${F2}_sorted.txt.sz
go run bloom.go ${H}_win_${F1}_${F2}_sorted.txt.sz ${F1} ${F2}
sztool -d ${D}${H}_win_${F1}_${F2}_bmatch.txt.sz | ${CSORT} -k1 | sztool -c - ${D}${H}_win_${F1}_${F2}_smatch.txt.sz
go run merge_bloom.go ${H}_win_${F1}_${F2}_sorted.txt.sz ${NX}
${CSORT} -o ${D}${H}_win_${F1}_${F2}_${NX}_rmatch.txt ${D}${H}_win_${F1}_${F2}_${NX}_rmatch.txt
